### ISSUE TITLE
Missing space between repo name and "updated at"

### ISSUE THREAD

**Issue by waldyrious** [philschatz/gh-board#19]
The fix should be pretty simple. I suppose it would go [here](https://github.com/philschatz/gh-board/blob/cf1babc09af4e933917bb3b78db6b7dd9c1dc37e/src/components/dashboard.jsx#L105-L107), but I have no idea about how the syntax of that file works :/

**Comment by waldyrious** [comment]
By the way, there's also a space missing between "All Open Issues and Pull Requests" (in the header) and the icon to its right

**Comment by philschatz** [comment]
Yep, that's the correct place; thanks!

**Comment by philschatz** [comment]
Oops, forgot to close this; it was merged in #22 back in July
