### ISSUE TITLE
Allow disabling the issue move confirmation dialog

### ISSUE THREAD

**Issue by waldyrious** [philschatz/gh-board#20]
When initially setting up a repo, or making large changes, it is quite annoying to have to confirm the move for every issue. Ideally there should be a way to disable the confirmation, or even better, suppressing it for a configurable amount of time (x minutes / the current session / forever / ...).

**Comment by philschatz** [comment]
Oh, nice! So something like the sudo functionality in GitHub? When you change settings in GitHub it asks you to log in (even if you are already logged in), but then waits 30minutes or so before prompting you for a login again

**Comment by waldyrious** [comment]
Well, kinda -- I'd rather the choice be explicit :) but I understand this adds complexity to the UI, so some clever heuristic would work too, and would already be a nice improvement over the current behavior.

**Comment by mathieudutour** [comment]
Actually I don't understand why there is a confirmation dialog. If you look at waffle/github project/etc., there is none

**Comment by philschatz** [comment]
The issue move dialog occurs in case there is a Pull Request that is linked to an Issue. If they are linked, then this dialog allows you to select which linked items to move as well. 

But it should definitely not show up if there are no linked items to move, that's yeah that is terribly annoying... 😄 

Example:

![image](https://cloud.githubusercontent.com/assets/253202/21965077/2dd17128-db26-11e6-87b6-d5a07d7c3dcf.png)

**Comment by mathieudutour** [comment]
Ah got it. Didn't see this dialog yet, only the empty one. I'll send a PR

**Comment by philschatz** [comment]
#59 should fix the issue. I'll merge when done testing 😄
