### ISSUE TITLE
TypeError when setting gh-token

### ISSUE THREAD

**Issue by rtyler** [philschatz/gh-board#39]
This is using a build from SHA1@fb54d0c.

When clicking on the "Save" button, the following exception is raised. I built with Node v4.6.0, so I'm not sure if that's the source of the issue.

```
login-modal.jsx:9 Uncaught TypeError: e.getValue is not a functiont.default.a.default.createClass.onSave @ login-modal.jsx:9r @ ReactErrorUtils.js:26a @ EventPluginUtils.js:85s @ EventPluginUtils.js:105p @ EventPluginHub.js:43m @ EventPluginHub.js:54n @ forEachAccumulated.js:24y.processEventQueue @ EventPluginHub.js:257r @ ReactEventEmitterMixin.js:17i.handleTopLevel @ ReactEventEmitterMixin.js:28i @ ReactEventListener.js:72i.perform @ Transaction.js:140d.batchedUpdates @ ReactDefaultBatchingStrategy.js:62i @ ReactUpdates.js:97m.dispatchEvent @ ReactEventListener.js:147
Client
```

![type-error](https://cloud.githubusercontent.com/assets/26594/20723782/c5207522-b620-11e6-99b4-5ced35052024.png)

### Workaround

In case anybody else hits this, entering the following into the JavaScript console got me signed in:

```javascript
window.localStorage.setItem('gh-token', "MYTOKENHERE")
```

**Comment by philschatz** [comment]
Thanks for finding this! It should be fixed in #61
