### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by brassington** [philschatz/gh-board#5]
Thanks for the fantastic work so far; could you add a license so it's clear whether I can adapt or modify the code for future use, thanks!

**Comment by philschatz** [comment]
Thanks for pinging me multiple times :smile: . Just got back from vacation and have been catching up on emails. Would AGPL work?

**Comment by brassington** [comment]
Sorry to catch you on vacation, hope you enjoyed some time away; just wasn't sure my email found the right inbox. :)

If you're willing to consider a more permissive license like an Apache or MIT, that'd be great. I'm not super familiar with AGPL, but it's similar copy-left like GPLv3?

I would like to jump in and help with features, and am primarily motivated to use this against the corporate Github instance my team uses at work...  It's your well-organized codebase, so no pressure in any particular direction.

**Comment by philschatz** [comment]
I added the license so hopefully that helps :smile:  Also, the newest version of the board uses IndexedDB to store closed Issues in your browser so:

- you can still link to them and they show up in the board
- _Soon:_ you can have burndown and other kinds of charts
- _Soon:_ you can search Issues for text in the body

I tested it in Chrome/FF/Safari/IE but if it does not work, please let me know and I can fix it.

**Comment by satra** [comment]
@philschatz - similar to @machineloop's request would it be possible to switch to a more permission license like apache 2?
