### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by waldyrious** [philschatz/gh-board#60]
I'm getting a `TypeError: n.getValue is not a function` when clicking the Save button in the sign-in dialog. I suppose that refers to [this line](https://github.com/philschatz/gh-board/blob/cac40c5/src/components/login-modal.jsx#L15). I'm using Firefox 50.1.0 on OS X 10.10.5, if that helps.

**Comment by philschatz** [comment]
Drat, that was broken with a React update (grr, not enough tests). Thanks for finding it!

Also, it looks like the preferred syntax for refs has changed again https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute

**Comment by waldyrious** [comment]
That was quick! :smile:
